var a=5;
console.log(a);
let a = "abhinav";
console.log(a);
const a = true ;
console.log(a);
var a = 1;
var b = "abhinav";
var c = true;
var d = new Object();
var arr = [1,2,3,4,"hello"];
console.log(typeof a); 
console.log(typeof b);
console.log(typeof c);
console.log(typeof d);
console.log(typeof arr);
var a = 5;
 a=10;
 console.log(a-5);
console.log(a);